universe = vanilla
executable = v25_200k_fixed/wrapper_mt_v25.sh
output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/mt_v25_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/mt_v25_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/mt_v25_$(ClusterId).log
request_cpus = 1
request_memory = 100GB
request_disk = 10GB
+JobFlavour = "tomorrow"
requirements = (OpSysAndVer =?= "AlmaLinux9")
queue
