universe = vanilla
executable = v24_50k_fixed/wrapper_mt_v24.sh
output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/mt_v24_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/mt_v24_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/mt_v24_$(ClusterId).log
request_cpus = 1
request_memory = 60GB
request_disk = 10GB
+JobFlavour = "tomorrow"
requirements = (OpSysAndVer =?= "AlmaLinux9")
queue
