executable              = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/ana/generate_cm_with_energy.py
arguments               = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/training_output/channel_tagging/ct_volume_simple/$(dir)
output                  = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/generate_cm_$(dir).out
error                   = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/generate_cm_$(dir).err
log                     = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/generate_cm_$(dir).log

request_cpus            = 1
request_memory          = 8GB
request_disk            = 2GB
request_gpus            = 1

+JobFlavour             = "espresso"

queue dir in (
20251113_014639
20251113_051316
20251113_040440
20251114_122620
20251114_123412
)
