executable = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/condor/condor_wrapper.sh
arguments = volume_v51_10k
output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v51_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v51_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v51_$(ClusterId).log

transfer_input_files = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_memory = 24GB
request_gpus = 1
requirements = ( OpSysAndVer == "AlmaLinux9" )

+JobFlavour = "tomorrow"

queue
