# Condor submit file for CT v37 hyperopt
universe                = vanilla
executable              = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/condor/wrapper_ct_simple.sh
arguments               = -j /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/json/volume_v37_hyperopt_10k.json

# Resource requests
request_cpus            = 4
request_memory          = 16GB
request_gpus            = 1
request_disk            = 5GB

# Job requirements
+JobFlavour             = "nextweek"
requirements            = (OpSysAndVer =?= "AlmaLinux9")

# Environment
getenv                  = True

# Output files
log                     = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_volume_v37_hyperopt_$(Cluster).log
output                  = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_volume_v37_hyperopt_$(Cluster).out
error                   = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_volume_v37_hyperopt_$(Cluster).err

# Notification
notification            = Error

# Submit
queue 1
