#!/bin/bash
# HTCondor submission script for CT v11: Deeper architecture (5 conv, 128 filters)

executable = channel_tagging/condor/wrapper_ct_streaming.sh
arguments = -j channel_tagging/json/volume_v11_deeper_100k.json

output = channel_tagging/logs/CT_v11_deeper_100k_$(ClusterId).out
error = channel_tagging/logs/CT_v11_deeper_100k_$(ClusterId).err
log = channel_tagging/logs/CT_v11_deeper_100k_$(ClusterId).log

request_cpus = 1
request_memory = 24GB
request_disk = 5GB

+JobFlavour = "tomorrow"
+AccountingGroup = "group_u_T2K-RE13.evilla"

queue
