universe = vanilla
executable = condor/wrapper_ct_volume_batch_reload.sh
arguments = -j /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/json/volume_v63_batch_reload_10k.json -p X -r 5
output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v63_batch_reload_10k_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v63_batch_reload_10k_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v63_batch_reload_10k_$(ClusterId).log
request_cpus = 1
request_memory = 60GB
request_disk = 10GB
request_GPUs = 1
+JobFlavour = "tomorrow"
requirements = (OpSysAndVer =?= "AlmaLinux9")
queue
