# Condor submit file for CT v41 - corrected data 50k
universe                = vanilla
executable              = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/condor/wrapper_ct_simple.sh
arguments               = -j /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/json/volume_v41_corrected_50k.json

# Resource requests
request_cpus            = 4
request_memory          = 45GB
request_gpus            = 1
request_disk            = 10GB

# Job requirements
+JobFlavour             = "nextweek"
requirements            = (OpSysAndVer =?= "AlmaLinux9")

# Working directory
initialdir              = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml

# Environment
getenv                  = True

# Output files
log                     = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v41_$(Cluster).log
output                  = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v41_$(Cluster).out
error                   = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v41_$(Cluster).err

# Notification
notification            = Error

# Submit
queue 1
