# HTCondor submission for CT v43 deep architecture
executable = channel_tagging/condor/wrapper_ct_deep.sh
arguments = -j channel_tagging/json/volume_v43_deep_100k.json

output = channel_tagging/logs/CT_v43_deep_$(ClusterId).out
error = channel_tagging/logs/CT_v43_deep_$(ClusterId).err
log = channel_tagging/logs/CT_v43_deep_$(ClusterId).log

request_cpus = 4
request_memory = 24GB
request_disk = 10GB
request_gpus = 1

+JobFlavour = "nextweek"
queue 1
