# HTCondor submission for CT v52 (batch reload strategy)
executable = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/condor/wrapper_ct_volume_batch_reload.sh
arguments = -j /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/json/volume_v52_batch_reload.json -p X -r 5

output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v52_batch_reload_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v52_batch_reload_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v52_batch_reload_$(ClusterId).log

request_cpus = 4
request_memory = 64GB
request_disk = 20GB
request_gpus = 1

+JobFlavour = "tomorrow"
queue 1
