#!/bin/bash
# HTCondor submission script for CT v9: 150k streaming

executable = channel_tagging/condor/wrapper_ct_streaming.sh
arguments = -j channel_tagging/json/volume_v9_streaming_150k.json

output = channel_tagging/logs/CT_v9_streaming_150k_$(ClusterId).out
error = channel_tagging/logs/CT_v9_streaming_150k_$(ClusterId).err
log = channel_tagging/logs/CT_v9_streaming_150k_$(ClusterId).log

request_cpus = 1
request_memory = 18GB
request_disk = 5GB

+JobFlavour = "tomorrow"
+AccountingGroup = "group_u_T2K-RE13.evilla"

queue
