executable              = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/condor/wrapper_ct_simple.sh
arguments               = -j channel_tagging/json/volume_v18_10k.json
output                  = channel_tagging/logs/CT_volume_v18_10k_$(ClusterId).out
error                   = channel_tagging/logs/CT_volume_v18_10k_$(ClusterId).err
log                     = channel_tagging/logs/CT_volume_v18_10k_$(ClusterId).log

request_cpus            = 4
request_memory          = 16GB
request_disk            = 5GB

+JobFlavour             = "workday"

queue 1
