#!/bin/bash
# HTCondor submission script for CT v12: Quick 10k test for plots verification

executable = channel_tagging/condor/wrapper_ct_streaming.sh
arguments = -j channel_tagging/json/volume_v12_test_10k.json

output = channel_tagging/logs/CT_v12_test_10k_$(ClusterId).out
error = channel_tagging/logs/CT_v12_test_10k_$(ClusterId).err
log = channel_tagging/logs/CT_v12_test_10k_$(ClusterId).log

request_cpus = 1
request_memory = 16GB
request_disk = 5GB

+JobFlavour = "tomorrow"
+AccountingGroup = "group_u_T2K-RE13.evilla"

queue
