executable = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/condor/wrapper_ct_simple.sh
arguments = -j channel_tagging/json/volume_v2_balanced_10k_nov10.json

output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v2_balanced_10k_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v2_balanced_10k_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/logs/CT_v2_balanced_10k_$(ClusterId).log

+AccountingGroup = "group_u_CMS.u_zh.users"
+JobFlavour = "workday"

request_cpus = 1
request_memory = 16GB
request_gpus = 1

queue 1
