#!/bin/bash
# HTCondor submission script for CT v13: 10k test WITHOUT streaming (should be much faster than v12)

executable = channel_tagging/condor/wrapper_ct_simple.sh
arguments = -j channel_tagging/json/volume_v13_test_10k.json

output = channel_tagging/logs/CT_v13_test_10k_$(ClusterId).out
error = channel_tagging/logs/CT_v13_test_10k_$(ClusterId).err
log = channel_tagging/logs/CT_v13_test_10k_$(ClusterId).log

request_cpus = 6
request_memory = 18GB
request_disk = 5GB

+JobFlavour = "tomorrow"
+AccountingGroup = "group_u_T2K-RE13.evilla"

queue
