executable              = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/channel_tagging/condor/wrapper_ct_simple.sh
arguments               = -j channel_tagging/json/volume_v27_50k.json
output                  = channel_tagging/logs/CT_volume_v27_50k_$(ClusterId).out
error                   = channel_tagging/logs/CT_volume_v27_50k_$(ClusterId).err
log                     = channel_tagging/logs/CT_volume_v27_50k_$(ClusterId).log

request_cpus            = 6
request_memory          = 24GB
request_disk            = 5GB

+JobFlavour             = "nextweek"

queue 1
