executable            = run_ct_v73_cropped_20k.sh
arguments             = 
output                = logs/ct_v73_cropped_20k.$(ClusterId).$(ProcId).out
error                 = logs/ct_v73_cropped_20k.$(ClusterId).$(ProcId).err
log                   = logs/ct_v73_cropped_20k.$(ClusterId).$(ProcId).log

+JobFlavour           = "nextweek"

request_cpus          = 4
request_memory        = 80GB
request_disk          = 15GB
request_gpus          = 1

queue 1
