#!/bin/bash
# HTCondor submission script for CT v15: 150k NO streaming

executable = channel_tagging/condor/wrapper_ct_simple.sh
arguments = -j channel_tagging/json/volume_v15_150k.json

output = channel_tagging/logs/CT_v15_150k_$(ClusterId).out
error = channel_tagging/logs/CT_v15_150k_$(ClusterId).err
log = channel_tagging/logs/CT_v15_150k_$(ClusterId).log

request_cpus = 6
request_memory = 24GB
request_disk = 5GB

+JobFlavour = "testmatch"
+AccountingGroup = "group_u_T2K-RE13.evilla"

queue
