executable            = scripts/run_single_plane_energy10_hyperopt.sh
output                = logs/single_plane_x_energy10_hyperopt_v4_$(ClusterId).out
error                 = logs/single_plane_x_energy10_hyperopt_v4_$(ClusterId).err
log                   = logs/single_plane_x_energy10_hyperopt_v4_$(ClusterId).log

+JobFlavour           = "testmatch"
request_gpus          = 1
request_memory        = 8GB

queue
