universe = vanilla
executable = scripts/condor_wrapper_electron_direction.sh

plane = X
max_samples = 
json_config = json/electron_direction/production_v4.json
arguments = $(plane) $(max_samples) $(json_config)

+RequestCpus = 1
request_cpus = 1
request_memory = 30GB
request_disk = 20GB
+MaxRunTime = 86400

log = logs/electron_direction_v4_$(Cluster).log
output = logs/electron_direction_v4_$(Cluster).out
error = logs/electron_direction_v4_$(Cluster).err

queue 1
