#!/bin/bash
# Condor submit file for ED v20 (mixed ES+CC with hyperopt)
executable            = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/condor/wrapper_ed_enhanced.sh
arguments             = -j electron_direction/json/three_plane_v20_200k_mixed_hyperopt.json
output                = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v20_mixed_hyperopt_$(ClusterId).out
error                 = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v20_mixed_hyperopt_$(ClusterId).err
log                   = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v20_mixed_hyperopt_$(ClusterId).log

# Resource requirements
request_cpus          = 8
request_memory        = 24GB
request_GPUs          = 1

+MaxRuntime           = 43200
+JobFlavour           = "tomorrow"

queue 1
