executable = electron_direction/condor/wrapper_ed_enhanced.sh
arguments = -j electron_direction/json/three_plane_v19_200k_deeper.json
output = electron_direction/logs/ED_v19_deeper_$(ClusterId).out
error = electron_direction/logs/ED_v19_deeper_$(ClusterId).err
log = electron_direction/logs/ED_v19_deeper_$(ClusterId).log

request_cpus = 4
request_memory = 24GB
request_gpus = 1
+MaxRuntime = 345600

+JobFlavour = "nextweek"
accounting_group = group_u_DUNE.users

queue 1
