#!/bin/bash
# Condor submit file for ED v21 (mixed ES+CC with fixed params from v14)
executable            = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/condor/wrapper_ed_enhanced.sh
arguments             = -j electron_direction/json/three_plane_v21_200k_mixed.json
output                = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v21_mixed_$(ClusterId).out
error                 = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v21_mixed_$(ClusterId).err
log                   = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v21_mixed_$(ClusterId).log

# Resource requirements
request_cpus          = 8
request_memory        = 24GB
request_GPUs          = 1

+MaxRuntime           = 43200
+JobFlavour           = "tomorrow"

queue 1
