# HTCondor submit file for v57 (reproduce v14 on 100k samples)
executable = wrapper_v55.sh
arguments = -j json/v57_reproduce_v14_100k.json
output = logs/ed_v57_reproduce_v14_100k_$(ClusterId).out
error = logs/ed_v57_reproduce_v14_100k_$(ClusterId).err
log = logs/ed_v57_reproduce_v14_100k_$(ClusterId).log

request_GPUs = 1
request_CPUs = 4
request_memory = 32GB
request_disk = 2GB

+JobFlavour = "tomorrow"

queue 1
