# HTCondor submission file for 3-plane ED with angular loss - 50k samples
executable = electron_direction/condor/condor_wrapper_3plane_simple.sh
arguments = -j electron_direction/json/three_plane_angular_v6_50k.json

output = electron_direction/logs/3plane_angular_v6_50k_$(ClusterId).out
error = electron_direction/logs/3plane_angular_v6_50k_$(ClusterId).err
log = electron_direction/logs/3plane_angular_v6_50k_$(ClusterId).log

request_cpus = 1
request_memory = 16GB
request_gpus = 1

+JobFlavour = "tomorrow"
+AccountingGroup = "group_u_DUNE.users"

queue 1
