# Condor submit file for ED v26 - corrected data 50k
universe                = vanilla
executable              = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/condor/wrapper_ed_enhanced.sh
arguments               = -j /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/json/three_plane_v26_50k_corrected.json

# Resource requests
request_cpus            = 4
request_memory          = 24GB
request_gpus            = 1
request_disk            = 10GB

# Job requirements
+JobFlavour             = "nextweek"
requirements            = (OpSysAndVer =?= "AlmaLinux9")

# Working directory
initialdir              = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml

# Environment
getenv                  = True

# Output files
log                     = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v26_$(Cluster).log
output                  = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v26_$(Cluster).out
error                   = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v26_$(Cluster).err

# Notification
notification            = Error

# Submit
queue 1
