universe = vanilla
executable = condor/wrapper_v54_simple.sh
output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ed_v54_simple.$(ClusterId).$(ProcId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ed_v54_simple.$(ClusterId).$(ProcId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ed_v54_simple.$(ClusterId).log
request_cpus = 1
request_gpus = 1
request_memory = 100GB
request_disk = 10GB
+JobFlavour = "tomorrow"
queue
