executable = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/scripts/wrapper_ed_three_plane.sh
arguments = -j /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/json/three_plane_v27_100k_corrected.json
output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v27_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v27_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v27_$(ClusterId).log
request_cpus = 4
request_memory = 40GB
request_gpus = 1
+AccountingGroup = "group_u_ATLASWISC.users"
+JobFlavour = "nextweek"
initialdir = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml
queue
