executable            = scripts/run_three_plane_energy10_hyperopt.sh
output                = logs/three_plane_energy10_hyperopt_v4_$(ClusterId).out
error                 = logs/three_plane_energy10_hyperopt_v4_$(ClusterId).err
log                   = logs/three_plane_energy10_hyperopt_v4_$(ClusterId).log

+JobFlavour           = "testmatch"
request_gpus          = 1
request_memory        = 8GB

queue
