#!/bin/bash
# Condor submit file for ED v22 (mixed ES+CC with incremental loading)
executable            = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/condor/condor_wrapper_3plane_incremental.sh
arguments             = -j electron_direction/json/three_plane_v22_200k_incremental.json
output                = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v22_incremental_$(ClusterId).out
error                 = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v22_incremental_$(ClusterId).err
log                   = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/logs/ED_v22_incremental_$(ClusterId).log

# Resource requirements
request_cpus          = 8
request_memory        = 16GB
request_GPUs          = 1

+MaxRuntime           = 43200
+JobFlavour           = "tomorrow"

queue 1
