executable            = run_ed_v02_5k.sh
arguments             = 
output                = logs/ed_v02_5k.$(ClusterId).$(ProcId).out
error                 = logs/ed_v02_5k.$(ClusterId).$(ProcId).err
log                   = logs/ed_v02_5k.$(ClusterId).$(ProcId).log
+JobFlavour           = "nextweek"

request_cpus          = 4
request_memory        = 60GB
request_disk          = 15GB
request_gpus          = 1

queue 1
