executable = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/electron_direction/condor/wrapper_ed_enhanced.sh
arguments             = three_plane_v29_100k_corrected.json
output                = logs/three_plane_v29_100k_corrected.out
error                 = logs/three_plane_v29_100k_corrected.err
log                   = logs/three_plane_v29_100k_corrected.log
request_gpus          = 1
request_memory        = 32GB
+JobFlavour           = "nextweek"
queue
