# HTCondor submission file for 3-plane ED with cosine loss - simple GPU requirement
executable = electron_direction/condor/condor_wrapper_3plane_simple.sh
arguments = -j electron_direction/json/three_plane_cosine_v6_10k.json

output = electron_direction/logs/3plane_cosine_v6_10k_simple_$(ClusterId).out
error = electron_direction/logs/3plane_cosine_v6_10k_simple_$(ClusterId).err
log = electron_direction/logs/3plane_cosine_v6_10k_simple_$(ClusterId).log

request_cpus = 1
request_memory = 12GB
request_gpus = 1

+JobFlavour = "workday"
+AccountingGroup = "group_u_DUNE.users"

queue 1
