executable = electron_direction/condor/condor_wrapper_3plane_simple.sh
arguments = -j electron_direction/json/three_plane_v12_100k.json
output = electron_direction/logs/three_plane_v12_100k_$(ClusterId).out
error = electron_direction/logs/three_plane_v12_100k_$(ClusterId).err
log = electron_direction/logs/three_plane_v12_100k_$(ClusterId).log

request_cpus = 1
request_memory = 24GB
request_gpus = 1
+MaxRuntime = 172800

accounting_group = group_u_DUNE.users

queue 1
