# HTCondor submission for MT v26_50k (Fixed with proper splits)
executable = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/condor/wrapper_mt_v26.sh
arguments = -j /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/json/v26_50k.json

output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v26_50k_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v26_50k_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v26_50k_$(ClusterId).log

request_cpus = 4
request_memory = 40GB
request_disk = 10GB
request_gpus = 1

+JobFlavour = "tomorrow"
queue 1
