# Condor submit file for MT v11 - corrected data 100k
universe                = vanilla
executable              = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/condor/wrapper_mt_incremental.sh
arguments               = -j /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/json/production_v11_corrected_100k.json

# Resource requests
request_cpus            = 4
request_memory          = 28GB
request_gpus            = 1
request_disk            = 15GB

# Job requirements
+JobFlavour             = "nextweek"
requirements            = (OpSysAndVer =?= "AlmaLinux9")

# Working directory
initialdir              = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml

# Environment
getenv                  = True

# Output files
log                     = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v11_$(Cluster).log
output                  = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v11_$(Cluster).out
error                   = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v11_$(Cluster).err

# Notification
notification            = Error

# Submit
queue 1
