executable = mt_identifier/condor/condor_wrapper_mt_v8.sh
arguments = -j mt_identifier/json/production_v10_100k_nov13.json
output = mt_identifier/logs/MT_v10_100k_$(ClusterId).out
error = mt_identifier/logs/MT_v10_100k_$(ClusterId).err
log = mt_identifier/logs/MT_v10_100k_$(ClusterId).log

request_cpus = 4
request_memory = 40GB
request_gpus = 1
+MaxRuntime = 172800

+JobFlavour = "testmatch"
accounting_group = group_u_DUNE.users

queue 1
