# HTCondor submission for MT v17 (best model retraining)
executable = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/condor/wrapper_mt_simple.sh
arguments = -j /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/json/production_v17_100k.json

output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v17_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v17_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v17_$(ClusterId).log

request_cpus = 4
request_memory = 24GB
request_disk = 10GB
request_gpus = 1

+JobFlavour = "nextweek"
queue 1
