executable = mt_identifier/condor/wrapper_mt_incremental.sh
arguments = -j mt_identifier/json/production_v13_incremental.json
output = mt_identifier/logs/MT_v13_incremental_$(ClusterId).out
error = mt_identifier/logs/MT_v13_incremental_$(ClusterId).err
log = mt_identifier/logs/MT_v13_incremental_$(ClusterId).log

request_cpus = 4
request_memory = 16GB
request_gpus = 1
+MaxRuntime = 172800

+JobFlavour = "testmatch"
accounting_group = group_u_DUNE.users

queue 1
