# HTCondor submission for MT v17 (best model retraining)
executable = mt_identifier/condor/wrapper_mt.sh
arguments = -j mt_identifier/json/production_v17_100k.json

output = mt_identifier/logs/MT_v17_$(ClusterId).out
error = mt_identifier/logs/MT_v17_$(ClusterId).err
log = mt_identifier/logs/MT_v17_$(ClusterId).log

request_cpus = 4
request_memory = 24GB
request_disk = 10GB
request_gpus = 1

+JobFlavour = "nextweek"
queue 1
