universe = vanilla
executable = scripts/condor_wrapper.sh

plane = X
max_samples = 
json_config = json/mt_identifier/production_v5.json
arguments = $(plane) $(max_samples) $(json_config)

request_cpus = 1
request_memory = 40GB
request_disk = 20GB
+MaxRunTime = 86400

log = logs/mt_identifier_v5_$(Cluster).log
output = logs/mt_identifier_v5_$(Cluster).out
error = logs/mt_identifier_v5_$(Cluster).err

queue 1
