executable = mt_identifier/condor/condor_wrapper_mt_v8.sh
arguments = -j mt_identifier/json/production_v9_nov11_10k.json
output = mt_identifier/logs/MT_v9_nov11_10k_$(ClusterId).out
error = mt_identifier/logs/MT_v9_nov11_10k_$(ClusterId).err
log = mt_identifier/logs/MT_v9_nov11_10k_$(ClusterId).log

request_cpus = 1
request_memory = 16GB
request_gpus = 1
+MaxRuntime = 86400

accounting_group = group_u_DUNE.users

queue 1
