executable = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/scripts/wrapper_mt.sh
arguments = -j /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/json/production_v11_corrected_100k.json
output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v11_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v11_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v11_$(ClusterId).log
request_cpus = 4
request_memory = 40GB
request_gpus = 1
+AccountingGroup = "group_u_ATLASWISC.users"
+JobFlavour = "nextweek"
initialdir = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml
queue
