# HTCondor submission for MT v20 (best model retraining)
executable = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/condor/wrapper_mt_simple.sh
arguments = -j /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/json/v20.json

output = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v20_$(ClusterId).out
error = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v20_$(ClusterId).err
log = /afs/cern.ch/work/e/evilla/private/dune/refactor_ml/mt_identifier/logs/MT_v20_$(ClusterId).log

request_cpus = 4
request_memory = 40GB
request_disk = 10GB
request_gpus = 1

+JobFlavour = "tomorrow"
queue 1
